apiVersion: batch/v1
kind: Job
metadata:
  name: simpledevice-ef-migrations
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: ef-migrations
          image: simpledevice-api:migrations
          command: ["dotnet", "ef", "database", "update"]
          envFrom:
            - configMapRef:
                name: simpledevice-api-config
            - secretRef:
                name: simpledevice-api-secrets
